// `.env.ts` is generated by the `npm run env` command
// `npm run env` exposes environment variables as JSON for any usage you might
// want, like displaying the version or getting extra config from your CI bot, etc.
// This is useful for granularity you might need beyond just the environment.
// Note that as usual, any environment variables you expose through it will end up in your
// bundle, and you should not use it for any sensitive information like passwords or keys.
import { env } from './.env';

export const environment = {
  production: true,
  version: env['npm_package_version'],
  serverUrl: 'https://api.chucknorris.io',
  defaultLanguage: 'en-US',
  supportedLanguages: ['en-US', 'es-ES'],
  firebase: {
    apiKey: 'AIzaSyC4vQ9zBhFMQsO79Z7cg3TQXobyb8p1sk8',
    authDomain: 'ejercicio-angular-b12d6.firebaseapp.com',
    databaseURL: 'https://ejercicio-angular-b12d6-default-rtdb.firebaseio.com',
    projectId: 'ejercicio-angular-b12d6',
    storageBucket: 'ejercicio-angular-b12d6.appspot.com',
    messagingSenderId: '399788064305',
    appId: '1:399788064305:web:e2446278424819f6685f10',
    measurementId: 'G-EX1XSZX3BP',
  },
};
